### ISSUE TITLE
raise FlickrError

### ISSUE THREAD

**Issue by infrontofme** [ultralytics/flickr_scraper#4]
Hi, when I run following script:
``` shell
python flickr_scraper.py --search 'honeybees on flowers' --n 10 --download
```
an error occurred.
```
Traceback (most recent call last):
  File "flickr_scraper.py", line 68, in <module>
    download=opt.download)  # download images
  File "flickr_scraper.py", line 33, in get_urls
    for i, photo in enumerate(photos):
  File "C:\Users\nanwa\anaconda3\lib\site-packages\flickrapi\core.py", line 688, in data_walker
    rsp = method(page=page, **params)
  File "C:\Users\nanwa\anaconda3\lib\site-packages\flickrapi\call_builder.py", line 38, in __call__
    return self.flickrapi_object.do_flickr_call(self.method_name, **kwargs)
  File "C:\Users\nanwa\anaconda3\lib\site-packages\flickrapi\core.py", line 337, in do_flickr_call
    **params)
  File "C:\Users\nanwa\anaconda3\lib\site-packages\flickrapi\core.py", line 407, in _wrap_in_parser
    return parser(self, data)
  File "C:\Users\nanwa\anaconda3\lib\site-packages\flickrapi\core.py", line 297, in parse_etree
    raise FlickrError(six.u('Error: %(code)s: %(msg)s') % err.attrib, code=code)
flickrapi.exceptions.FlickrError: Error: 100: Invalid API Key (Key has invalid format)
```
I tried both on windows and ubuntu, reports the same error

**Comment by berkantay** [comment]
did you embed your api and secret key to the flicker_scraper.py

**Comment by glenn-jocher** [comment]
@infrontofme @berkantay you need to use your own API key, as the README explains:

# Use

1. Request a Flickr API key: https://www.flickr.com/services/apps/create/apply

2. Write your API key and secret in `flickr_scraper.py` L9-L10:
```python
key = ''
secret = ''
```

**Comment by glenn-jocher** [comment]
Thanks for reporting this. PR #45 has been merged and improves the credential workflow so users no longer have to edit the source file only.

Supported options now are:

```bash
export FLICKR_API_KEY="YOUR_API_KEY"
export FLICKR_API_SECRET="YOUR_API_SECRET"
python3 flickr_scraper.py --search "honeybees on flowers" --n 10 --download
```

or:

```bash
python3 flickr_scraper.py --search "honeybees on flowers" --n 10 --download --key YOUR_API_KEY --secret YOUR_API_SECRET
```

Remaining limitation: Flickr can still return an API error for invalid credentials or service-side failures, but the script now reports that error directly instead of failing vaguely.

**Comment by UltralyticsAssistant** [comment]
A potential fix for this issue has now been merged in [PR #45: Improve Flickr scraper compatibility and CI](https://github.com/ultralytics/flickr_scraper/pull/45) by @glenn-jocher.

The merged changes that may resolve this include:

- Improved Flickr credential handling with `FLICKR_API_KEY` and `FLICKR_API_SECRET` environment variables
- New `--key` and `--secret` CLI overrides
- Replacing the older `flickrapi.walk()` flow with direct `photos.search` JSON responses for better compatibility
- Added pagination via `--page` to continue scraping later result pages
- Better URL construction and fallback handling when original image URLs are unavailable
- Improved API/request error handling with clearer failure messages
- Safer download behavior with explicit HTTP error checks
- Added automated tests and CI to help prevent regressions
- README updates covering setup, pagination, duplicate handling, and compatibility notes

Thanks to @glenn-jocher and contributors for the fix and improvements.

If you'd like to test whether this resolves the issue before the next release, you can install the latest `main` branch directly:

```bash
pip install git+https://github.com/ultralytics/flickr_scraper.git@main
```

Otherwise, waiting for the next official PyPI release is also an option.

If possible, please test the updated code and share whether it resolves the issue. Thanks 🙏 for reporting this, and any further feedback is welcome if the issue still persists.
