### ISSUE TITLE
Script won't pull photos

### ISSUE THREAD

**Issue by Fahrenheit** [ultralytics/flickr_scraper#5]
I attempted to use the command suggested and have tried to pull other things however I always get this error. It creates the necessary folders, but won't grab any of the photos. Not quite sure how to fix this. Any help would be much appreciated!

```
`flickr_scraper` % python3 flickr_scraper.py --search 'honeybees' --n 10 --download           
Traceback (most recent call last):
  File "/Users/fah/Projects/flickr_scraper/flickr_scraper.py", line 62, in <module>
    get_urls(search=opt.search,  # search term
  File "/Users/fah/Projects/flickr_scraper/flickr_scraper.py", line 31, in get_urls
    for i, photo in enumerate(photos):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flickrapi/core.py", line 690, in data_walker
    photoset = rsp.getchildren()[0]
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'
```

**Comment by glenn-jocher** [comment]
@Fahrenheit script works correctly, just tested it today 16 January 2021 in a Colab notebook.

<img width="1222" alt="Screen Shot 2021-01-16 at 9 22 00 PM" src="https://user-images.githubusercontent.com/26833433/104831803-ec449180-5840-11eb-8710-a8780697a143.png">

**Comment by Fahrenheit** [comment]
> @Fahrenheit script works correctly, just tested it today 16 January 2021 in a Colab notebook.
> 
> <img alt="Screen Shot 2021-01-16 at 9 22 00 PM" width="1222" src="https://user-images.githubusercontent.com/26833433/104831803-ec449180-5840-11eb-8710-a8780697a143.png">

Odd, I still can't get it to work.

**Comment by glenn-jocher** [comment]
@Fahrenheit are you using the Flickr API key and secret as in the README instructions?
https://github.com/ultralytics/flickr_scraper#use

**Comment by Fahrenheit** [comment]
> @Fahrenheit are you using the Flickr API `key` and `secret` as in the README instructions?
> https://github.com/ultralytics/flickr_scraper#use

Yes, I am. I'll try a new API key and see if that works.

**Comment by guillaumedavidphd** [comment]
I think this might be related to the deprecation of `getchildren` in Python 3.9. See https://docs.python.org/3.8/library/xml.etree.elementtree.html#xml.etree.ElementTree.Element.getchildren.

**Comment by glenn-jocher** [comment]
@guillaumedavidphd thanks for the info! We don't use this in ultralytics/flickr_scraper but I see it is used in the flickrapi package. 

@Fahrenheit perhaps downgrading your python to 3.8 might solve this?

**Comment by gpotte** [comment]
Thanks this worked !!

**Comment by snippsat** [comment]
Hi i did help with someone with this error on python-forum.io   
First show how to run Python 3.8 in environment  with **py**(no need to downgrade)  
```
# Make environment with Python 3.8 
G:\div_code\py -3.8 -m venv flick38_env  
```
Then i looked at error.    
In **core.py** line 690.  
```
#photoset = rsp.getchildren()[0]  
photoset = list(rsp)[0] # Fix for Python 3.9
```
Test with Python 3.9  
```
(flick_env) G:\div_code\flick_env\flickr_scraper (master)
λ python flickr_scraper.py --search "bees" --n 10 --download
0/10 https://live.staticflickr.com/5537/14142817779_8786627929_o.jpg
1/10 https://live.staticflickr.com/829/41747732682_f4f10ec204_o.jpg
2/10 https://live.staticflickr.com/1662/23809746334_c22950a054_o.jpg
3/10 https://live.staticflickr.com/4094/4822128168_415b5ce1e4_o.jpg
4/10 https://farm6.staticflickr.com/5511/12638717365_7643b6e19a_b.jpg
5/10 https://live.staticflickr.com/961/27921370568_0795b91dfb_o.jpg
6/10 https://farm2.staticflickr.com/1646/26540040015_54f071db32_b.jpg
7/10 https://farm8.staticflickr.com/7377/26868463353_6da2da165d_b.jpg
8/10 https://farm8.staticflickr.com/7595/17187249975_b1ccddea5f_b.jpg
9/10 https://farm2.staticflickr.com/1578/26186589965_678bd3c5a4_b.jpg
```

**Comment by yx135790** [comment]
> > Hi i did help with someone with this error on python-forum.io First show how to run Python 3.8 in environment with **py**(no need to downgrade)
> > ```
> > # Make environment with Python 3.8 
> > G:\div_code\py -3.8 -m venv flick38_env  
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then i looked at error. In **core.py** line 690.
> > ```
> > #photoset = rsp.getchildren()[0]  
> > photoset = list(rsp)[0] # Fix for Python 3.9
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Test with Python 3.9
> > ```
> > (flick_env) G:\div_code\flick_env\flickr_scraper (master)
> > λ python flickr_scraper.py --search "bees" --n 10 --download
> > 0/10 https://live.staticflickr.com/5537/14142817779_8786627929_o.jpg
> > 1/10 https://live.staticflickr.com/829/41747732682_f4f10ec204_o.jpg
> > 2/10 https://live.staticflickr.com/1662/23809746334_c22950a054_o.jpg
> > 3/10 https://live.staticflickr.com/4094/4822128168_415b5ce1e4_o.jpg
> > 4/10 https://farm6.staticflickr.com/5511/12638717365_7643b6e19a_b.jpg
> > 5/10 https://live.staticflickr.com/961/27921370568_0795b91dfb_o.jpg
> > 6/10 https://farm2.staticflickr.com/1646/26540040015_54f071db32_b.jpg
> > 7/10 https://farm8.staticflickr.com/7377/26868463353_6da2da165d_b.jpg
> > 8/10 https://farm8.staticflickr.com/7595/17187249975_b1ccddea5f_b.jpg
> > 9/10 https://farm2.staticflickr.com/1578/26186589965_678bd3c5a4_b.jpg
> > ```
> 
> thank you.. you saved me

worked for me ,thanks

**Comment by sinhakrishnendu** [comment]
@beautytasara27 you save me, thank you so much.

**Comment by glenn-jocher** [comment]
Thanks to everyone who helped narrow this down. PR #45 has been merged and avoids the old `flickrapi.walk()` code path that triggered the Python 3.9+ `getchildren()` error.

Current command:

```bash
export FLICKR_API_KEY="YOUR_API_KEY"
export FLICKR_API_SECRET="YOUR_API_SECRET"
python3 flickr_scraper.py --search "honeybees on flowers" --n 10 --download
```

Remaining limitation: this still depends on Flickr returning valid results for the search and credentials; service-side Flickr errors are now reported with the API message.

**Comment by UltralyticsAssistant** [comment]
A potential fix for this issue has now been merged in [PR #45: Improve Flickr scraper compatibility and CI](https://github.com/ultralytics/flickr_scraper/pull/45) by @glenn-jocher.

The merged changes that may resolve this include:

- Improved Flickr credential handling with `FLICKR_API_KEY` and `FLICKR_API_SECRET` environment variables
- New `--key` and `--secret` CLI overrides
- Replacing the older `flickrapi.walk()` flow with direct `photos.search` JSON responses for better compatibility
- Added pagination via `--page` to continue scraping later result pages
- Better URL construction and fallback handling when original image URLs are unavailable
- Improved API/request error handling with clearer failure messages
- Safer download behavior with explicit HTTP error checks
- Added automated tests and CI to help prevent regressions
- README updates covering setup, pagination, duplicate handling, and compatibility notes

Thanks to @glenn-jocher and contributors for the fix and improvements.

If you'd like to test whether this resolves the issue before the next release, you can install the latest `main` branch directly:

```bash
pip install git+https://github.com/ultralytics/flickr_scraper.git@main
```

Otherwise, waiting for the next official PyPI release is also an option.

If possible, please test the updated code and share whether it resolves the issue. Thanks 🙏 for reporting this, and any further feedback is welcome if the issue still persists.
