### ISSUE TITLE
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren' when running python3 flickr_scraper.py

### ISSUE THREAD

**Issue by cjgetty** [ultralytics/flickr_scraper#8]
```
Traceback (most recent call last):
  File "/Users/cjgetty/Desktop/flickr_scraper/flickr_scraper.py", line 66, in <module>
    get_urls(search=opt.search,  # search term
  File "/Users/cjgetty/Desktop/flickr_scraper/flickr_scraper.py", line 31, in get_urls
    for i, photo in enumerate(photos):
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/flickrapi/core.py", line 690, in data_walker
    photoset = rsp.getchildren()[0]
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'
```

**Comment by s4lm-xi** [comment]
I was able to fix the issue myself by editing the `core.py` file. The file should be inside the following path `python3.x/site-packages/flickrapi/core.py`

replace line 690 with `photoset = list(rsp)[0]`. That should resolve the issue

`getchildren` method is deprecated, check out the [documentation](https://docs.python.org/2/library/xml.etree.elementtree.html#element-objects)

**Comment by glenn-jocher** [comment]
@s4lm-xi thanks for the fix idea! Can you please submit a PR with your updates to help future uses?

**Comment by s4lm-xi** [comment]
the issue is from the `flickrapi` module. The current latest version is `2.4.0` and it doesn't include the fix. however in the `flickr` github [repo](https://github.com/sybrenstuvel/flickrapi) the issue is fixed. But there is not an available version to install.

**Comment by glenn-jocher** [comment]
Got it, thanks!

**Comment by 15177759775** [comment]
It works.Thanks!

**Comment by rmozart** [comment]
Thanks, @s4lm-xi ! It worked real nice!

**Comment by UltralyticsAssistant** [comment]
A potential fix for this issue has now been merged in [PR #45: Improve Flickr scraper compatibility and CI](https://github.com/ultralytics/flickr_scraper/pull/45) by @glenn-jocher.

The merged changes that may resolve this include:

- Improved Flickr credential handling with `FLICKR_API_KEY` and `FLICKR_API_SECRET` environment variables
- New `--key` and `--secret` CLI overrides
- Replacing the older `flickrapi.walk()` flow with direct `photos.search` JSON responses for better compatibility
- Added pagination via `--page` to continue scraping later result pages
- Better URL construction and fallback handling when original image URLs are unavailable
- Improved API/request error handling with clearer failure messages
- Safer download behavior with explicit HTTP error checks
- Added automated tests and CI to help prevent regressions
- README updates covering setup, pagination, duplicate handling, and compatibility notes

Thanks to @glenn-jocher and contributors for the fix and improvements.

If you'd like to test whether this resolves the issue before the next release, you can install the latest `main` branch directly:

```bash
pip install git+https://github.com/ultralytics/flickr_scraper.git@main
```

Otherwise, waiting for the next official PyPI release is also an option.

If possible, please test the updated code and share whether it resolves the issue. Thanks 🙏 for reporting this, and any further feedback is welcome if the issue still persists.

**Comment by glenn-jocher** [comment]
Thanks for the detailed traceback and workaround notes. PR #45 has been merged and fixes this in the scraper by using Flickr JSON `photos.search` directly instead of `flickrapi.walk()`, so the deprecated `getchildren()` path is avoided on Python 3.9 and newer.

Current command:

```bash
export FLICKR_API_KEY="YOUR_API_KEY"
export FLICKR_API_SECRET="YOUR_API_SECRET"
python3 flickr_scraper.py --search "honeybees on flowers" --n 10 --download
```

Remaining limitation: this does not patch `flickrapi` itself for other projects; it removes this repository's dependency on the broken walker path.
